apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: gitea-ingress
  namespace: git
spec:
  rules:
  - host: git.domain.placeholder
    http:
      paths:
      - backend:
          serviceName: gitea-http
          servicePort: 3000